name: GHAS to CSV data report run
on: [push]
jobs:
  data-gathering:
    runs-on: ubuntu-latest
    steps:
      - name: CSV export
        uses: advanced-security/ghas-to-csv@v2
        env:
          GITHUB_PAT: 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
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: shelby-test-org
          
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: ghas-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error
